### ISSUE TITLE
consider using pseudoc

### ISSUE THREAD

**Issue by psifertex** [WhatTheFuzz/binaryninja-openai#11]
The API to get it out is a [bit awkward](https://gist.github.com/psifertex/6fbc7532f536775194edd26290892ef7#file-pseudo_c-py) right now, but I expect PseudoC would give better results than HLIL.

**Comment by WhatTheFuzz** [comment]
For sure. Though I am still surprised HLIL works so well. I'll implement it in a future release. Thanks!
