### ISSUE TITLE
Failed to import plugin: No module named 'openai.api_resources'

### ISSUE THREAD

**Issue by dzervas** [WhatTheFuzz/binaryninja-openai#29]
I imagine that the openai module got a breaking update at some point and the plugin no longer works

**Comment by ChrisKader** [comment]
It seems `api_resources` was renamed to `resources` in version 1.0.0

https://github.com/openai/openai-python/discussions/742#discussion-5829467

`openai.api_resources -> openai.resources`

**Comment by WhatTheFuzz** [comment]
Hey, sorry. I didn't mean to disappear without addressing this. 😬 The latest release, from PR #30, should resolve this. Could anyone confirm? Binary Ninja should scrape the repo and update the plugin manager later this week. Until then, you may have to manually symlink the project to the Binja plugins folder.

**Comment by WhatTheFuzz** [comment]
Closing this issue since it's been a few months without hiccup. Please reopen if you experience issues.
