### ISSUE TITLE
Query blocks main thread.

### ISSUE THREAD

**Issue by WhatTheFuzz** [WhatTheFuzz/binaryninja-openai#8]
Sending the query to OpenAI is not done concurrently. This can cause Binary Ninja to hang and have the OS report that it has frozen. Users can wait it out, but it should really be done on a concurrent thread.

**Comment by psifertex** [comment]
You could use a [BackgroundTaskThread](https://api.binary.ninja/binaryninja.plugin-module.html#binaryninja.plugin.BackgroundTaskThread). See, eg:

https://github.com/Martyx00/ghinja/blob/master/decompiler.py#L7-L27

**Comment by WhatTheFuzz** [comment]
Easy enough, I'll implement it for the next release. Thanks for the example code!
